# Generated by Django 4.1.7 on 2023-02-20 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_rename_orderitems_orderitem_product_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='digital',
            new_name='delivery',
        ),
    ]
