# Generated by Django 4.1.7 on 2023-02-21 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_rename_digital_product_delivery'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='delivery',
            new_name='deliverys',
        ),
    ]
