# Generated by Django 4.1.7 on 2023-02-21 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_rename_delivery_product_deliverys'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='deliverys',
            field=models.BooleanField(default=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=7),
        ),
    ]
